### ISSUE TITLE
Problem with RSS Feed

### ISSUE THREAD

**Issue by ghost** [repnz/repnz.github.io#1]
Hello,
I'm liking your blog so far! However my RSS-Aggregator miniflux isn't able to properly display your feed and link to your articles. As a feed source it's using https://repnz.github.io/posts/index.xml.
I think the problem lies in you using relative links in your XML items (e.g. `<link>/posts/crt-find-main/</link>`) as opposed to something like `<link>https://repnz.github.io/posts/crt-find-main/</link>`.

Hope you'll be able to fix this, looking forward to further blog posts

**Comment by repnz** [comment]
Hey, Thanks for the feedback!
I'm pretty new to blogging, sorry for the inconvenience.
Actually, I'm working right now on my next post, I will fix this when I release the next blog ;)

**Comment by theevilbit** [comment]
Hi,

Just wanted to report the same :) The fix is simple, in the config.toml file in Hugo add:
baseurl = "https://repnz.github.io"
and regenerate content, that should be it. I just fixed it for my site as well :D

Thanks,
Csaba

**Comment by repnz** [comment]
Hey,
Sorry for the late reply. I solved the issue like you suggested, ping me if there are problems:)
